ArNetworking: ArServerCommands Class Reference
ArServerCommands Class Reference
The commands from the server to the client.
#include <ArServerCommands.h>
Public Types
enum ServerCommands {
SHUTDOWN = 1, INTRODUCTION = 2, UDP_INTRODUCTION = 3, UDP_CONFIRMATION = 4,
CONNECTED = 5, REJECTED = 6, TCP_ONLY = 7, LIST = 129,
LISTSINGLE = 130, LISTARGRET = 131, LISTARGRETSINGLE = 132, LISTGROUPANDFLAGS = 133,
LISTGROUPANDFLAGSSINGLE = 134
}
enum Type { TYPE_UNSPECIFIED = 0, TYPE_REAL = 1, TYPE_SIMULATED = 2, TYPE_NONE = 3 }
Static Public Member Functions
static const char * toString (Type type)
Detailed Description
The commands from the server to the client.
Member Enumeration Documentation
enum ArServerCommands::ServerCommands
Enumerator:
SHUTDOWN
Closes the connection.
INTRODUCTION
Introduces the server to the client.
UDP_INTRODUCTION
Udp introduction of the server to the client.
UDP_CONFIRMATION
Confirmation Udp was received from client.
CONNECTED
Server accepts clients connection.
REJECTED
Server rejects clients connection, has a byte2, then a string.... these reasons (1 = bad username password, string then is empty, 2 = rejecting connection because using central server, string then is central server IP, 3 = client rejecting server because server has wrong protocol, 4 = server rejected client because client has wrong protocol, 5 = maxClients exceeded, 6 = type of client is specified, but doesn't match)
TCP_ONLY
Server tells client to only send TCP.
LIST
Map of the string names for a type to a number along with a long description of the data type.
LISTSINGLE
Map of a single type to a number (for late additions to server) along with its description.
LISTARGRET
Map of the number to their arguments and returns descriptions.
LISTARGRETSINGLE
Map of a single type to a number (for late additions to server) along with its argument and return descriptions.
LISTGROUPANDFLAGS
Map of the number to their command groups and data flags.
LISTGROUPANDFLAGSSINGLE
Map of a single type to a number (for late additions to server) along with its command group and data flags.
enum ArServerCommands::Type
Enumerator:
TYPE_UNSPECIFIED
TYPE_REAL
Unspecified (anything can connect)
Only real robots permitted to connect
TYPE_SIMULATED
Only simulated robots permitted to connect.
TYPE_NONE
Nothing is permitted to connect.
Member Function Documentation
static const char* ArServerCommands::toString (Type type) inline static
References TYPE_NONE, TYPE_REAL, TYPE_SIMULATED, and TYPE_UNSPECIFIED.
Referenced by ArCentralManager::enforceType(), ArClientSwitchManager::enforceType(), ArServerBase::enforceType(), ArClientBase::enforceType(), and ArClientSwitchManager::runThread().
The documentation for this class was generated from the following file:
ArServerCommands.h