ArNetworking: TestProvider Class Reference
TestProvider Class Reference
Public Member Functions
int get ()
void inc ()
void lock ()
TestProvider ()
void unlock ()
Constructor & Destructor Documentation
TestProvider::TestProvider () inline
Member Function Documentation
int TestProvider::get () inline
Referenced by main().
void TestProvider::inc () inline
Referenced by main().
void TestProvider::lock (void) inline
References ArMutex::lock().
Referenced by main().
void TestProvider::unlock (void) inline
References ArMutex::unlock().
Referenced by main().
The documentation for this class was generated from the following file:
dataPubExample.cpp